// <auto-generated />
using System;
using EcoBackend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoBackend.Infrastructure.Migrations
{
    [DbContext(typeof(EcoDbContext))]
    [Migration("20260327111359_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoBackend.Core.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActivityDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("ActivityTime")
                        .HasColumnType("interval");

                    b.Property<int>("ActivityTypeId")
                        .HasColumnType("integer");

                    b.Property<double>("CO2Impact")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAutoDetected")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("integer");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.ActivityCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ActivityCategories");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.ActivityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CO2Impact")
                        .HasColumnType("double precision");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImpactUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEcoFriendly")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ActivityTypes");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PointsReward")
                        .HasColumnType("integer");

                    b.Property<string>("RequirementCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequirementType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RequirementValue")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BadgeType = "transport",
                            Description = "Log your first walking activity",
                            Icon = "🚶",
                            IsActive = true,
                            Name = "First Steps",
                            PointsReward = 10,
                            RequirementCategory = "walking",
                            RequirementType = "activities_count",
                            RequirementValue = 1.0
                        },
                        new
                        {
                            Id = 2,
                            BadgeType = "transport",
                            Description = "Walk a total of 10 km",
                            Icon = "🚶",
                            IsActive = true,
                            Name = "Walker",
                            PointsReward = 25,
                            RequirementCategory = "walking",
                            RequirementType = "distance",
                            RequirementValue = 10.0
                        },
                        new
                        {
                            Id = 3,
                            BadgeType = "transport",
                            Description = "Cycle a total of 20 km",
                            Icon = "🚲",
                            IsActive = true,
                            Name = "Cyclist",
                            PointsReward = 30,
                            RequirementCategory = "cycling",
                            RequirementType = "distance",
                            RequirementValue = 20.0
                        },
                        new
                        {
                            Id = 4,
                            BadgeType = "transport",
                            Description = "Use public transit 20 times",
                            Icon = "🚌",
                            IsActive = true,
                            Name = "Transit Pro",
                            PointsReward = 35,
                            RequirementCategory = "public_transit",
                            RequirementType = "activities_count",
                            RequirementValue = 20.0
                        },
                        new
                        {
                            Id = 5,
                            BadgeType = "transport",
                            Description = "Run a total of 50 km",
                            Icon = "🏃",
                            IsActive = true,
                            Name = "Marathon Runner",
                            PointsReward = 50,
                            RequirementCategory = "running",
                            RequirementType = "distance",
                            RequirementValue = 50.0
                        },
                        new
                        {
                            Id = 6,
                            BadgeType = "transport",
                            Description = "Use eco-friendly transport 50 times",
                            Icon = "🌍",
                            IsActive = true,
                            Name = "Eco Commuter",
                            PointsReward = 100,
                            RequirementCategory = "eco_transport",
                            RequirementType = "activities_count",
                            RequirementValue = 50.0
                        },
                        new
                        {
                            Id = 7,
                            BadgeType = "food",
                            Description = "Log vegan for a whole day",
                            Icon = "🌱",
                            IsActive = true,
                            Name = "Vegan Day",
                            PointsReward = 20,
                            RequirementCategory = "vegan",
                            RequirementType = "activities_count",
                            RequirementValue = 1.0
                        },
                        new
                        {
                            Id = 8,
                            BadgeType = "food",
                            Description = "Eat vegan for 7 consecutive days",
                            Icon = "🥬",
                            IsActive = true,
                            Name = "Vegan Week",
                            PointsReward = 60,
                            RequirementCategory = "vegan",
                            RequirementType = "streak",
                            RequirementValue = 7.0
                        },
                        new
                        {
                            Id = 9,
                            BadgeType = "food",
                            Description = "Buy local produce 10 times",
                            Icon = "🥕",
                            IsActive = true,
                            Name = "Local Hero",
                            PointsReward = 30,
                            RequirementCategory = "local",
                            RequirementType = "activities_count",
                            RequirementValue = 10.0
                        },
                        new
                        {
                            Id = 10,
                            BadgeType = "food",
                            Description = "Log vegetarian meals for 5 days",
                            Icon = "🥗",
                            IsActive = true,
                            Name = "Vegetarian",
                            PointsReward = 40,
                            RequirementCategory = "vegetarian",
                            RequirementType = "streak",
                            RequirementValue = 5.0
                        },
                        new
                        {
                            Id = 11,
                            BadgeType = "food",
                            Description = "Log 15 zero waste cooking activities",
                            Icon = "♻️",
                            IsActive = true,
                            Name = "Zero Waste Chef",
                            PointsReward = 50,
                            RequirementCategory = "zero_waste",
                            RequirementType = "activities_count",
                            RequirementValue = 15.0
                        },
                        new
                        {
                            Id = 12,
                            BadgeType = "energy",
                            Description = "Log solar panelling 30 times",
                            Icon = "☀️",
                            IsActive = true,
                            Name = "Energy Saver",
                            PointsReward = 75,
                            RequirementCategory = "solar",
                            RequirementType = "activities_count",
                            RequirementValue = 30.0
                        },
                        new
                        {
                            Id = 13,
                            BadgeType = "energy",
                            Description = "Switch to LED bulbs 5 times",
                            Icon = "💡",
                            IsActive = true,
                            Name = "Light Master",
                            PointsReward = 35,
                            RequirementCategory = "led",
                            RequirementType = "activities_count",
                            RequirementValue = 5.0
                        },
                        new
                        {
                            Id = 14,
                            BadgeType = "energy",
                            Description = "Document 20 energy saving actions",
                            Icon = "⚡",
                            IsActive = true,
                            Name = "Power Manager",
                            PointsReward = 60,
                            RequirementCategory = "power_saving",
                            RequirementType = "activities_count",
                            RequirementValue = 20.0
                        },
                        new
                        {
                            Id = 15,
                            BadgeType = "energy",
                            Description = "Use renewable energy sources for 10 days",
                            Icon = "🌊",
                            IsActive = true,
                            Name = "Renewable Champion",
                            PointsReward = 80,
                            RequirementCategory = "renewable",
                            RequirementType = "streak",
                            RequirementValue = 10.0
                        },
                        new
                        {
                            Id = 16,
                            BadgeType = "recycling",
                            Description = "Log 15 recycling activities",
                            Icon = "♻️",
                            IsActive = true,
                            Name = "Recycling Hero",
                            PointsReward = 40,
                            RequirementCategory = "recycling",
                            RequirementType = "activities_count",
                            RequirementValue = 15.0
                        },
                        new
                        {
                            Id = 17,
                            BadgeType = "recycling",
                            Description = "Recycle for 10 consecutive days",
                            Icon = "🛡️",
                            IsActive = true,
                            Name = "Waste Warrior",
                            PointsReward = 70,
                            RequirementCategory = "recycling",
                            RequirementType = "streak",
                            RequirementValue = 10.0
                        },
                        new
                        {
                            Id = 18,
                            BadgeType = "recycling",
                            Description = "Log 20 upcycling activities",
                            Icon = "🎨",
                            IsActive = true,
                            Name = "Upcycler",
                            PointsReward = 55,
                            RequirementCategory = "upcycling",
                            RequirementType = "activities_count",
                            RequirementValue = 20.0
                        },
                        new
                        {
                            Id = 19,
                            BadgeType = "recycling",
                            Description = "Compost for 7 consecutive days",
                            Icon = "🌿",
                            IsActive = true,
                            Name = "Compost Champion",
                            PointsReward = 45,
                            RequirementCategory = "composting",
                            RequirementType = "streak",
                            RequirementValue = 7.0
                        },
                        new
                        {
                            Id = 20,
                            BadgeType = "recycling",
                            Description = "Use no plastic products for 3 days",
                            Icon = "🚫",
                            IsActive = true,
                            Name = "Plastic Free",
                            PointsReward = 50,
                            RequirementCategory = "plastic_free",
                            RequirementType = "streak",
                            RequirementValue = 3.0
                        },
                        new
                        {
                            Id = 21,
                            BadgeType = "general",
                            Description = "Plant a tree",
                            Icon = "🌳",
                            IsActive = true,
                            Name = "Tree Planter",
                            PointsReward = 100,
                            RequirementCategory = "tree_planting",
                            RequirementType = "activities_count",
                            RequirementValue = 1.0
                        },
                        new
                        {
                            Id = 22,
                            BadgeType = "general",
                            Description = "Earn 500 eco points",
                            Icon = "👑",
                            IsActive = true,
                            Name = "Eco Champion",
                            PointsReward = 200,
                            RequirementCategory = "general",
                            RequirementType = "eco_points",
                            RequirementValue = 500.0
                        },
                        new
                        {
                            Id = 23,
                            BadgeType = "general",
                            Description = "Maintain 7-day streak",
                            Icon = "🔥",
                            IsActive = true,
                            Name = "Week Warrior",
                            PointsReward = 80,
                            RequirementCategory = "general",
                            RequirementType = "streak",
                            RequirementValue = 7.0
                        },
                        new
                        {
                            Id = 24,
                            BadgeType = "general",
                            Description = "Maintain 30-day streak",
                            Icon = "🏆",
                            IsActive = true,
                            Name = "Month Master",
                            PointsReward = 300,
                            RequirementCategory = "general",
                            RequirementType = "streak",
                            RequirementValue = 30.0
                        },
                        new
                        {
                            Id = 25,
                            BadgeType = "general",
                            Description = "Save 100 kg of CO2",
                            Icon = "💚",
                            IsActive = true,
                            Name = "Century Saver",
                            PointsReward = 150,
                            RequirementCategory = "general",
                            RequirementType = "co2_saved",
                            RequirementValue = 100.0
                        },
                        new
                        {
                            Id = 26,
                            BadgeType = "general",
                            Description = "Save 500 kg of CO2",
                            Icon = "💪",
                            IsActive = true,
                            Name = "Carbon Crusher",
                            PointsReward = 500,
                            RequirementCategory = "general",
                            RequirementType = "co2_saved",
                            RequirementValue = 500.0
                        });
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BadgeRewardId")
                        .HasColumnType("integer");

                    b.Property<string>("ChallengeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("PointsReward")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TargetActivityTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("TargetUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TargetValue")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BadgeRewardId");

                    b.HasIndex("TargetActivityTypeId");

                    b.HasIndex("TargetCategoryId");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.DailyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AcHours")
                        .HasColumnType("double precision");

                    b.Property<double>("BikeKm")
                        .HasColumnType("double precision");

                    b.Property<double>("BusKm")
                        .HasColumnType("double precision");

                    b.Property<double>("CarKm")
                        .HasColumnType("double precision");

                    b.Property<bool>("CompostedToday")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("EcoScore")
                        .HasColumnType("double precision");

                    b.Property<double>("ElectricityKwh")
                        .HasColumnType("double precision");

                    b.Property<int>("FishMeals")
                        .HasColumnType("integer");

                    b.Property<double>("FoodWasteKg")
                        .HasColumnType("double precision");

                    b.Property<double>("HeatingHours")
                        .HasColumnType("double precision");

                    b.Property<double>("InternetHours")
                        .HasColumnType("double precision");

                    b.Property<int>("LocalFoodItems")
                        .HasColumnType("integer");

                    b.Property<int>("MeatMeals")
                        .HasColumnType("integer");

                    b.Property<double>("NaturalGasTherms")
                        .HasColumnType("double precision");

                    b.Property<int>("PoultryMeals")
                        .HasColumnType("integer");

                    b.Property<bool>("RecycledToday")
                        .HasColumnType("boolean");

                    b.Property<int>("RedMeatMeals")
                        .HasColumnType("integer");

                    b.Property<int>("ReusableItems")
                        .HasColumnType("integer");

                    b.Property<string>("ScoreCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ShowerFrequency")
                        .HasColumnType("integer");

                    b.Property<int>("SingleUsePlasticItems")
                        .HasColumnType("integer");

                    b.Property<double>("TotalCO2")
                        .HasColumnType("double precision");

                    b.Property<double>("TrainMetroKm")
                        .HasColumnType("double precision");

                    b.Property<double>("TvPcHours")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UsedCooling")
                        .HasColumnType("boolean");

                    b.Property<bool>("UsedHeating")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("VegMeals")
                        .HasColumnType("integer");

                    b.Property<int>("VeganMeals")
                        .HasColumnType("integer");

                    b.Property<int>("VegetarianMeals")
                        .HasColumnType("integer");

                    b.Property<double>("WalkKm")
                        .HasColumnType("double precision");

                    b.Property<double>("WaterUsageLiters")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("DailyLogs");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.DailyScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CO2Emitted")
                        .HasColumnType("double precision");

                    b.Property<double>("CO2Saved")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("Steps")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("DailyScores");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.DeviceToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Token")
                        .IsUnique();

                    b.ToTable("DeviceTokens");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.EmailVerificationToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("EmailVerificationTokens");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.LocationPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Accuracy")
                        .HasColumnType("double precision");

                    b.Property<double>("ActivityConfidence")
                        .HasColumnType("double precision");

                    b.Property<double?>("Altitude")
                        .HasColumnType("double precision");

                    b.Property<string>("DetectedActivity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TripId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("LocationPoints");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.MonthlyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageDailyScore")
                        .HasColumnType("double precision");

                    b.Property<int>("BadgesEarned")
                        .HasColumnType("integer");

                    b.Property<string>("CategoryBreakdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ChallengesCompleted")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DailyBreakdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<int>("TotalActivities")
                        .HasColumnType("integer");

                    b.Property<double>("TotalCO2Emitted")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalCO2Saved")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("MonthlyReports");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TargetId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.NotificationPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AchievementAlerts")
                        .HasColumnType("boolean");

                    b.Property<bool>("CommunityUpdates")
                        .HasColumnType("boolean");

                    b.Property<bool>("DailyReminders")
                        .HasColumnType("boolean");

                    b.Property<bool>("TipsAndSuggestions")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<bool>("WeeklyReports")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("NotificationPreferences");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.PredictionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PredictedScore")
                        .HasColumnType("double precision");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PredictionLogs");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.PredictionTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<double>("EndLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("EndLongitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("StartLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("StartLongitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransportMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("PredictionTrips");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.Tip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImpactDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tips");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.TravelSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CarKm")
                        .HasColumnType("double precision");

                    b.Property<double>("CyclingKm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("OtherKm")
                        .HasColumnType("double precision");

                    b.Property<double>("PublicTransitKm")
                        .HasColumnType("double precision");

                    b.Property<int>("Steps")
                        .HasColumnType("integer");

                    b.Property<double>("TotalCO2Emitted")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalCO2Saved")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalKm")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalTrips")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<double>("WalkingKm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("TravelSummaries");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CO2Emitted")
                        .HasColumnType("double precision");

                    b.Property<double>("CO2Saved")
                        .HasColumnType("double precision");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<double?>("EndLatitude")
                        .HasColumnType("double precision");

                    b.Property<string>("EndLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("EndLongitude")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsAutoDetected")
                        .HasColumnType("boolean");

                    b.Property<double?>("StartLatitude")
                        .HasColumnType("double precision");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("StartLongitude")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("interval");

                    b.Property<string>("TransportMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TripDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("ActivityRecognition")
                        .HasColumnType("boolean");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("CalendarAccess")
                        .HasColumnType("boolean");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("boolean");

                    b.Property<int>("EcoScore")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleAuthId")
                        .HasColumnType("text");

                    b.Property<bool>("HealthDataSync")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("LastActivityDate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<bool>("LocationTracking")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("integer");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<double>("TotalCO2Saved")
                        .HasColumnType("double precision");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleAuthId")
                        .IsUnique()
                        .HasFilter("\"GoogleAuthId\" IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.UserBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BadgeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserId", "BadgeId")
                        .IsUnique();

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.UserChallenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CurrentProgress")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("UserId", "ChallengeId")
                        .IsUnique();

                    b.ToTable("UserChallenges");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.UserEcoProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CarFuelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CompostingPracticed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DietType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HouseholdSize")
                        .HasColumnType("integer");

                    b.Property<string>("LifestyleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RecyclingPracticed")
                        .HasColumnType("boolean");

                    b.Property<double>("RenewableEnergyPercent")
                        .HasColumnType("double precision");

                    b.Property<bool>("SmartThermostat")
                        .HasColumnType("boolean");

                    b.Property<string>("SocialActivity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<bool>("UsesSolarPanels")
                        .HasColumnType("boolean");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WasteBagSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserEcoProfiles");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.UserGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CurrentValue")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<double>("TargetValue")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserGoals");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.WeeklyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("GeneralWasteKg")
                        .HasColumnType("double precision");

                    b.Property<double>("GroceryBill")
                        .HasColumnType("double precision");

                    b.Property<int>("NewClothesMonthly")
                        .HasColumnType("integer");

                    b.Property<double>("RecycledWasteKg")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("WasteBagCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "WeekStartDate")
                        .IsUnique();

                    b.ToTable("WeeklyLogs");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.WeeklyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageDailyScore")
                        .HasColumnType("double precision");

                    b.Property<string>("CategoryBreakdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ComparisonToAverage")
                        .HasColumnType("double precision");

                    b.Property<double>("ComparisonToPrevious")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalActivities")
                        .HasColumnType("integer");

                    b.Property<double>("TotalCO2Emitted")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalCO2Saved")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("WeekEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("WeekStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "WeekStart")
                        .IsUnique();

                    b.ToTable("WeeklyReports");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.Activity", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.ActivityType", "ActivityType")
                        .WithMany("Activities")
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoBackend.Core.Entities.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.ActivityType", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.ActivityCategory", "Category")
                        .WithMany("ActivityTypes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.Challenge", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.Badge", "BadgeReward")
                        .WithMany()
                        .HasForeignKey("BadgeRewardId");

                    b.HasOne("EcoBackend.Core.Entities.ActivityType", "TargetActivityType")
                        .WithMany()
                        .HasForeignKey("TargetActivityTypeId");

                    b.HasOne("EcoBackend.Core.Entities.ActivityCategory", "TargetCategory")
                        .WithMany()
                        .HasForeignKey("TargetCategoryId");

                    b.Navigation("BadgeReward");

                    b.Navigation("TargetActivityType");

                    b.Navigation("TargetCategory");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.ChatMessage", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.ChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.ChatSession", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.User", "User")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.DailyLog", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.DailyScore", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.User", "User")
                        .WithMany("DailyScores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.DeviceToken", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.LocationPoint", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.Trip", "Trip")
                        .WithMany("Points")
                        .HasForeignKey("TripId");

                    b.HasOne("EcoBackend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.MonthlyReport", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.Notification", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.NotificationPreference", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.User", "User")
                        .WithOne("NotificationPreferences")
                        .HasForeignKey("EcoBackend.Core.Entities.NotificationPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.PredictionLog", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.PredictionTrip", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.Tip", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.ActivityCategory", "Category")
                        .WithMany("Tips")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.TravelSummary", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.Trip", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.User", "User")
                        .WithMany("Trips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.UserBadge", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoBackend.Core.Entities.User", "User")
                        .WithMany("Badges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.UserChallenge", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.Challenge", "Challenge")
                        .WithMany("UserChallenges")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoBackend.Core.Entities.User", "User")
                        .WithMany("Challenges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.UserEcoProfile", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.User", "User")
                        .WithOne("EcoProfile")
                        .HasForeignKey("EcoBackend.Core.Entities.UserEcoProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.UserGoal", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.WeeklyLog", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.WeeklyReport", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoBackend.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("EcoBackend.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.ActivityCategory", b =>
                {
                    b.Navigation("ActivityTypes");

                    b.Navigation("Tips");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.ActivityType", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.Challenge", b =>
                {
                    b.Navigation("UserChallenges");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.Trip", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("EcoBackend.Core.Entities.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Badges");

                    b.Navigation("Challenges");

                    b.Navigation("ChatSessions");

                    b.Navigation("DailyScores");

                    b.Navigation("EcoProfile");

                    b.Navigation("Goals");

                    b.Navigation("NotificationPreferences");

                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
